### ISSUE TITLE
Which point of contact should a customer inquire when they have a trouble with quickstart ?

### ISSUE THREAD

**Issue by Shumpei-Kubo-IBM** [aws-quickstart/quickstart-ibm-icp-for-data#22]
Which point of contact should a customer inquire when they have a trouble with quickstart ?
AWS ? or IBM ?

**Comment by vsnyc** [comment]
@Shumpei-Kubo-IBM You can start with the Quick Start team, opening an issue here. We can give general guidance looking at the CloudFormation event logs and bootstrap logs for the deployment. Further deep dive may require going to AWS support if the issue is found to be related to an AWS service or to IBM support if the issue is for the Cloud Pak for Data product. This repository is watched by both AWS and IBM teams.

**Comment by Shumpei-Kubo-IBM** [comment]
Many thanks, @vsnyc san !
and how can a customer call quick start team ?
sorry for the basic question ...

**Comment by vsnyc** [comment]
@Shumpei-Kubo-IBM san - my apologies for the delay. The customer can open a new issue here on GitHub itself, for example, see this issue reported for a previous version of the quick start: https://github.com/aws-quickstart/quickstart-ibm-icp-for-data/issues/10. Alternatively, we can also be reached at `quickstart [at] amazon [dot] com`.
