### ISSUE TITLE
Changing the load balancer type from CLB to NLB for the master load balancer.

### ISSUE THREAD

**Issue by htkmts** [aws-quickstart/quickstart-ibm-icp-for-data#26]
Hi.

According to the deployment guide, I understand that a CLB (Classic Load Balancer) is deployed for the master load balancer.

https://aws-quickstart.s3.amazonaws.com/quickstart-ibm-icp-for-data/doc/ibm-cloud-pak-for-data-on-the-aws-cloud.pdf
"A Master Load Balancer, which spans the private subnets, for accessing the OCP compute nodes. This provides web-browser access to Cloud Pak for Data."

Are there any ways I can change the CLB to an NLB AFTER the installation?
(I need a static IP address for the load balancer and CLB does not support static IPs.)

Thanks.

**Comment by shaithal** [comment]
We have not tried changing CLB to NLB. Since it is IPI ( Installer provisioned infrastructure) everything is done by Openshift during cluster creation. 

One way to use NLB is to go with UPI ( user provisioned infrastructure) where you can bring resource and then deploy openshift on top of defined resources.

**Comment by htkmts** [comment]
Thanks!
