### ISSUE TITLE
Undocumented worker limit of 10 nodes?

### ISSUE THREAD

**Issue by durera** [aws-quickstart/quickstart-ibm-icp-for-data#8]
Is there a specific reason the quickstart is limited to 10 workers?

`WorkerNodeStack` failed to create due to ValidationError while creating the AutoScaling group `WorkerNodeAutoScalingGroup`: `Desired capacity:20 must be between the specified min size:1 and max size:10 (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: xxx)`

The [quickstart documentation](https://aws-quickstart.s3.amazonaws.com/quickstart-ibm-icp-for-data/doc/ibm-cloud-private-for-data-on-the-aws-cloud.pdf) makes no mention of a maximum limit for workers, perhaps I am misunderstanding the error though, not overly familiar with AWS CloudFormation:
> The number of worker nodes (desired capacity) to be deployed in the IBM Cloud Private for Data cluster. A minimum of 3 nodes is required.

**Comment by shaithal** [comment]
Hi @durera  Since this was an initial release with just UG&I and cognos addons we did not expect the worker node count to be more than 10. 

Can you please give your scenario, so that we can possibly either document or increase the ASG limit judiciously.

**Comment by durera** [comment]
We are working on getting Watson IoT Platform (https://internetofthings.ibmcloud.com/) running in ICP4D at the moment.  Our intent is to use this quickstart to see how WIoTP on ICP4D behaves specifically when deployed on AWS.  After an initial sizing we thought 20 workers is a reasonable estimate to fit everything in.

**Comment by vsnyc** [comment]
@durera I have increased the [worker limit to 40](https://github.com/aws-quickstart/quickstart-ibm-cloud-private/commit/e856956705723d8d3de7e8cf936ea5647afe56f5). It will merge to master once the tests complete. Might take a few days since we have an upcoming change in development right now. If you want to try this in the develop branch, please follow the instructions in our [contributor's guide](https://aws-quickstart.github.io/option1.html).
